name: Release 'object-observer'

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.OO_CI_AT }}

      - name: Setup NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NPM
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish
        run: |
          echo registry=https://registry.npmjs.org/ > .npmrc
          echo //registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN} >> .npmrc
          npm publish
          rm .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Bump version to next snapshot
      - name: Bump snapshot version
        run: |
          npm run bump -- --version=patch --snapshot
          echo "SNAPSHOT_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git fetch
          git config user.email "gullerya@gmail.com"
          git config user.name "object-observer CI"
          git add --all
          git commit -m "set version to ${{ env.SNAPSHOT_VERSION }}"
          git push origin HEAD:master